---
title: "Tarea 2"
author: "Juan Alberto Mora"
date: '2022-06-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Carga de datos

```{r Carga-datos, echo=FALSE, include=FALSE}
library(DT)
library(ggplot2)
library(plotly)
library(readxl)
library(forcats)
library(dplyr)
library(tidyverse)
library(lubridate)
setwd("C:/Users/Gustavo/Documents/Tarea 2 procesamiento de datos")
```
## Conversión de datos

```{r conversion-de-datos, warnings=FALSE}
datos_oij <- read_excel("estadisticaspoliciales2021.xls", 
    col_types = c("text", "skip", "date", 
        "skip", "text", "skip", "text", "text", 
        "skip", "text", "text", "skip"))
datos_oij <- mutate(datos_oij, Caso = c(1:38349))
datos_oij <-
  datos_oij %>%
  select(Fecha, Delito, Victima, Edad, Genero, Provincia, Canton, Caso) %>%
  mutate(Fecha = as.Date(Fecha, format = "%Y/%m/%d"))
```

## Tabla DT

```{r Tabla-DT, echo=FALSE, warning=FALSE}
datos_oij %>%
  datatable(options = list(
    pageLength = 15,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'),
    colnames(datos_oij) <- c("Delito","Fecha","Víctima","Edad","Género","Provincia")
  ))
```

## Gráfico barras 1

```{r Grafico-barras-1, echo=FALSE, warning=FALSE}
ggplot2_delitos <-
datos_oij %>%
count(Delito) %>%
ggplot(aes(x = reorder(Delito, n), y = n)) +
geom_bar(stat = "identity") +
ggtitle("Cantidad de delitos por delito") +
xlab("Delito") +
ylab("Cantidad") + 
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
ggplotly(ggplot2_delitos) %>% config(locale = 'es')
```

## Gráfico barras 2

```{r grafico-barras-2, echo=FALSE, warning=FALSE}
ggplot2_delitos_por_mes <-
  datos_oij %>%
  mutate(fecha = lubridate::month(Fecha))
mes <-
  c(
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre"
  )
  ggplot2_delitos_por_mes <- ggplot2_delitos_por_mes %>%
  count(fecha) %>%
  ggplot(aes(x = reorder(fecha, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por mes") +
  xlab("Mes") +
  ylab("Cantidad") +
  theme()
  
ggplotly(ggplot2_delitos_por_mes) %>% config(locale = 'es')
```

## Gráfico barras 3

```{r grafico-barras-3, echo=FALSE, warning=FALSE}
ggplot2_delitos_por_genero <-
  datos_oij %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Cantidad de delitos por género") +
  xlab("Delito") +
  ylab("Cantidad") +
  labs(fill = "Género") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(ggplot2_delitos_por_genero) %>% config(locale = 'es')
```

## Gráfico barras 4

```{r grafico-barras-4, echo=FALSE, warning=FALSE}
ggplot2_delitos_por_canton <-
datos_oij %>%
filter(Provincia == c("SAN JOSE","ALAJUELA","CARTAGO","HEREDIA")) %>%
count(Canton) %>%
ggplot(aes(x = reorder(Canton, n), y = n)) +
geom_bar(stat = "identity") +
ggtitle("Cantidad de delitos por Canton") +
xlab("Cantón") +
ylab("Cantidad") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(ggplot2_delitos_por_canton) %>% config(locale = 'es')
```

